### ISSUE TITLE
Parsing WPx-datanodes.tsv files

### ISSUE THREAD

**Issue by ariutta** [wikipathways/meta-data-action#1]
These aren't always being serialized/parsed consistently. Examples:

WP5064-datanodes.tsv
```
ChEH    Protein P34913  Uniprot-TrEMBL  AKA cholesterol epoxide hydrolase (ChEH); EC: 3.3.2.11</br>"ChEH is a dimer of 7-dehydrocholesterol reductase (DHCR7) and 3β-hydroxysteroid-Δ8-Δ7-isomerase (D8D7I)"
```

WP5114-datanodes.tsv 
```
XPA GeneProduct ENSG00000136936 Ensembl "Furthermore, the DDB2 complex-mediated ubiquitylation plays a role in recruiting XPA to damaged sites".
```

WP5166-datanodes.tsv
```
LDH Protein 1.1.1.27    BRENDA  In book it says "(R)-lactate dehydrogenase" - investigate</br>L-Lactate dehydrogenase
...
1P5CDH  Protein 1.2.1.88    BRENDA  1-pyrroline-5-carboxylate dehydrogenase</br>Add "EC" with EC identifier?
```

~~This may be due to the change I made here for the parameters for parsing quoted fields:
https://github.com/wikipathways/wikipathways-database/commit/288ce733e1607777c6ede0b290c4639382da3e29#diff-f3a0c6cf05b703b1241cd9c83a3c9efad10e6e84ce8f1246f0ffd25e1f2b8fcbL82~~ *Update:* the jekyll site is parsing the TSV files independently of my script.

~~The annotations CSV files do use quotes to indicate fields, so I changed all the parsing to support quoted fields. @mkutmon, do you want to change the serialization of WPx-datanodes.tsv files to support quoted fields, or should we use `quoting=csv.QUOTE_NONE` [here](https://github.com/wikipathways/wikipathways-database/blob/0df9006d360f4234b2e5bc0c810f6bb8ae1bdf4c/scripts/create_pathway_frontmatter.py#L164) when parsing WPx-datanodes.tsv files?~~

**Comment by AlexanderPico** [comment]
I identified 32 busted tsvs and removed them so the site is building again. You can find them here:
https://github.com/wikipathways/wikipathways.github.io/tree/main/bad%20md%20and%20tsv%20files

**Comment by mkutmon** [comment]
- [ ] Fix order of data nodes 
- [ ] Fix comments with special characters

**Comment by ariutta** [comment]
Tina, using a TSV/CSV library that handles escaping special characters might be the most reliable solution. However, if there are no stray tab characters, we might be able to get away with just specifying `quoting=csv.QUOTE_NONE` [here](https://github.com/wikipathways/wikipathways-database/blob/0df9006d360f4234b2e5bc0c810f6bb8ae1bdf4c/scripts/create_pathway_frontmatter.py#L164).

**Comment by ariutta** [comment]
I specified `quoting=csv.QUOTE_NONE` as a temporary fix. We can remove it if you change the format of the datanode TSVs.

**Comment by mkutmon** [comment]
@ariutta can you check if the new data nodes comment format solves the issue?
