### ISSUE TITLE
Repeated ChEBI identifiers in datanodes.tsv

### ISSUE THREAD

**Issue by hasanbalci** [wikipathways/meta-data-action#11]
I noticed that all ChEBI identifiers are repeated in the datanodes.tsv files, e.g. "chebi:3165;chebi:3165", while there is no problem for other identifiers. It might be good to fix this for consistency.

**Comment by egonw** [comment]
Fix implemented.

**Comment by egonw** [comment]
Released: https://github.com/wikipathways/meta-data-action/releases/tag/v1.1.3
