### ISSUE TITLE
Remove redundant rows

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/meta-data-action#13]
As an example, this pathway lists MIR34A 6 times: 
https://www.wikipathways.org/pathways/WP4963.html

As long as there are no unique comments per datanode, it seems like we should add a step to prune for unique rows, right?

Making the datanodes.tsv unique will then automatically propagate to the tables displayed and downloaded from the website.

**Comment by egonw** [comment]
Implementation done.

**Comment by egonw** [comment]
Released in v1.1.4

**Comment by egonw** [comment]
Should output separate lines of comments are different too. I missed that :(

**Comment by egonw** [comment]
Fixed again.
